example:
  property: DEFAULT EXAMPLE
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      db:
        enabled: true
      diskspace:
        enabled: true
spring:
# STREAM, KAFKA
  cloud:
    stream:
      bindings:
        input:
          destination: orgChangeTopic
          content-type: application/json
          group: licenseGroup
      kafka:
        binder:
          zkNodes: zookeeper
          brokers: kafka
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.solvd.ikaravai: DEBUG
server:
  port: 8090
# KEYCLOAK
keycloak:
  realm: ms-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: msprac
  credentials:
    secret: rpjxRAMhSaRK1JaBiI5WVoLvkBv8Gxyv
  use-resource-role-mappings: true
  bearer-only: true
# REDIS
redis:
  server: redis
  port: 6379