management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: refresh, beans, env
  endpoint:
    health:
      enabled: true
      show-details: always
      db:
        enabled: true
      diskspace:
        enabled: true
spring:
# STREAMS, KAFKA
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          zkNodes: zookeeper
          brokers: kafka
  zipkin:
    baseUrl: http://zipkin:9411
  sleuth:
    sampler:
      percentage: 1
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
  datasource:
    url: jdbc:postgresql://postgres:5432/ms_prac
    username: postgres
    password: postgres
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
    com.solvd.ikaravai: DEBUG
server:
  port: 8091
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://my-eureka-service:8070/eureka
# KEYCLOAK
keycloak:
  realm: ms-realm
  auth-server-url: http://keycloak:8080/auth
  ssl-required: external
  resource: msprac
  credentials:
    secret: cTB4fi95e5uF6KBfrzV8zJ8FMcWtMChs
  use-resource-role-mappings: true
  bearer-only: true