version: '3.8'

services:
  my-lic-service:
    image: license-service
    container_name: my-lic-service
    ports:
      - "8080:8080"
    environment:
      - "SPRING_PROFILE_ACTIVE=dev"
    restart: unless-stopped
