spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/mybatis
    username: postgres
    password: postgres
  sql:
    init:
      schema-locations: classpath:/sql/schema.sql
      data-locations: classpath:/sql/data.sql
server:
  port: 9090
mybatis:
  config-location: classpath:/mybatis/mybatis.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
  type-aliases-package: com.solvd.ikaravai.mybatisservice.model
logging:
  level:
    com.solvd.ikaravai.mybatisservice.mapper: TRACE