apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-user: dXNlcg==
  postgres-password: cGFzc3dvcmQ=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  postgres-url: jdbc:postgresql://postgres:5432/mybatis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mybatis-service-deployment
  labels:
    app: mybatis-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mybatis-service
  template:
    metadata:
      labels:
        app: mybatis-service
    spec:
      containers:
        - name: mybatis-service
          image: ikaravai/jbogor:1.1
          ports:
            - containerPort: 9090
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres-url
---
apiVersion: v1
kind: Service
metadata:
  name: mybatis-service-service
spec:
  type: NodePort
  selector:
    app: mybatis-service
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 31000